Insert into FILTERS (ID_REQUEST,ID_UNITA_DOC,ID_DOC,ID_SESSIONE_VERS,ID_STRUT,DT_APERTURA_YY,ROWLIMIT,ID_COMP,ID_VER_INDICE_AIP,ID_VER_SERIE) 
values (1,10,100,1000,8,2023,1,10000,null,null);

Insert into FILTERS (ID_REQUEST,ID_UNITA_DOC,ID_DOC,ID_SESSIONE_VERS,ID_STRUT,DT_APERTURA_YY,ROWLIMIT,ID_COMP,ID_VER_INDICE_AIP,ID_VER_SERIE) 
values (2,null,null,null,8,2024,1,null,null,null);

Insert into FILTERS (ID_REQUEST,ID_UNITA_DOC,ID_DOC,ID_SESSIONE_VERS,ID_STRUT,DT_APERTURA_YY,ROWLIMIT,ID_COMP,ID_VER_INDICE_AIP,ID_VER_SERIE) 
values (3,null,null,null,8,2024,1,null,null,null);

Insert into FILTERS (ID_REQUEST,ID_UNITA_DOC,ID_DOC,ID_SESSIONE_VERS,ID_STRUT,DT_APERTURA_YY,ROWLIMIT,ID_COMP,ID_VER_INDICE_AIP,ID_VER_SERIE) 
values (4,null,null,null,8,2024,1,null,null,null);

Insert into FILTERS (ID_REQUEST,ID_UNITA_DOC,ID_DOC,ID_SESSIONE_VERS,ID_STRUT,DT_APERTURA_YY,ROWLIMIT,ID_COMP,ID_VER_INDICE_AIP,ID_VER_SERIE) 
values (6,null,null,null,8,2024,1,null,1000,null);

Insert into FILTERS (ID_REQUEST,ID_UNITA_DOC,ID_DOC,ID_SESSIONE_VERS,ID_STRUT,DT_APERTURA_YY,ROWLIMIT,ID_COMP,ID_VER_INDICE_AIP,ID_VER_SERIE) 
values (10,null,null,null,8,2024,1,null,null,1000);
